
# Documentation
# https://docs.aws.amazon.com/lumberyard/latest/userguide/waf-third-party-library-configurations.html

def build(bld):
    bld.DefineGem(

        # Compiler Specific
         win_cxxflags = [
            '/WX-'
        ],

        includes    = [
                        bld.Path('Code/CryEngine/CryCommon'),
                        bld.Path('Code/CryEngine/CryAction'),
                        'C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\Include'
                       ],

        # General
        file_list               = ['sr.waf_files'],

        win_stlibpath = ['C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\Lib\\x64'],
    )
